title: "Mathieu Carbou"
description: "Lead Software Engineer, Terracotta R&D, IBM"
logo: https://avatars.githubusercontent.com/u/61346
show_downloads: false
github:
  is_project_page: false
  is_user_page: true
  owner_name: Mathieu Carbou
  owner_url: https://github.com/mathieucarbou
  repository_url: https://github.com/mathieucarbou
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
